name: flutter_dicee
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/d1.png
    - images/d2.png
    - images/d3.png
    - images/d4.png
    - images/d5.png
    - images/d6.png

